plugins {
    id('java')
    id('eclipse')
    id('idea')
    id('net.neoforged.moddev').version('2.0.107')
}

group = mod_group_id
version = mod_version

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(java_version)
    }
    withSourcesJar()
}

def runsFolder = layout.projectDirectory.dir('runs')

neoForge {
    enable {
        version = neo_version
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    runs {
        configureEach {
            loadedMods = [mods."${mod_id}"]
        }
        client {
            client()
            gameDirectory.value(runsFolder.dir('client'))
        }
        server {
            server()
            gameDirectory.value(runsFolder.dir('server'))
        }
    }
}

static void exclusiveRepo(RepositoryHandler handler, String url, String... groups) {
    handler.exclusiveContent {
        it.forRepositories(handler.maven { setUrl(url) })
        it.filter { f -> for (def group : groups) { f.includeGroup(group) } }
    }
}

repositories {
    exclusiveRepo(repositories, 'https://modmaven.dev/', 'mekanism')
    exclusiveRepo(repositories, 'https://maven.shedaniel.me/', 'me.shedaniel', 'me.shedaniel.cloth')
    exclusiveRepo(repositories, 'https://maven.architectury.dev/', 'dev.architectury')
}

dependencies {
    compileOnly "mekanism:Mekanism:${mekanism_version}:api"
    compileOnly "mekanism:Mekanism:${mekanism_version}"
    runtimeOnly "mekanism:Mekanism:${mekanism_version}"

    compileOnly "me.shedaniel:RoughlyEnoughItems-api-neoforge:${rei_version}"
    compileOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}"
    runtimeOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}"
}

tasks.named('processResources', ProcessResources) {
    def replaceProperties = [
            mod_id             : mod_id,
            mod_name           : mod_name,
            mod_license        : mod_license,
            mod_version        : mod_version,
            mod_authors        : mod_authors,
            minecraft_version_range: minecraft_version_range,
            neo_version_range  : neo_version_range,
            loader_version_range: loader_version_range,
            mekanism_version_range: mekanism_version_range,
            rei_version_range  : rei_version_range,
    ]
    inputs.properties replaceProperties
    filesMatching('META-INF/neoforge.mods.toml') {
        expand replaceProperties
    }
}
