org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

java_version=21
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.200
neo_version_range=[21.1.194,)
loader_version_range=[4,)

mod_id=reimekanismintegration
mod_name=REI - Mekanism Integration
mod_license=MIT
mod_version=1.0.0
mod_authors=zenith
mod_group_id=com.zenith.reimekanismintegration

mekanism_version=1.21.1-10.7.19.85
mekanism_version_range=[10.7.15,)

rei_version=16.0.788
rei_version_range=[16.0.0,)
